# Generated by Django 5.1.3 on 2024-12-20 18:40

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('speciality', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('board_reg_no', models.CharField(max_length=100, unique=True)),
                ('system_reg_no', models.CharField(max_length=20, unique=True)),
                ('average_time_per_patient', models.IntegerField(default=20, validators=[demo.models.Doctor.validate_duration])),
                ('active', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('board_reg_cert', models.FileField(blank=True, null=True, upload_to=demo.models.Doctor.generateCertFileNameWithPath)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('Type', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=2)),
                ('last_number', models.IntegerField()),
            ],
        ),
    ]
